[book]
title = "Ninjago Rush"
authors = ["ninjago-rush"]
src = "src"
description = "Three ways to play Ninjago Rush"
language = "en"
multilingual = false

[output.html]
git-repository-url = "https://github.com/ninjago-rush/ninjago-rush.github.io"
